### ISSUE TITLE
Cant get player name from objective

### ISSUE THREAD

**Issue by TAC-Studios** [EvModder/EvStats#2]
I'm using PlayerNPC which supports PAPI and I've set the placeholder to be %objective_entryposhigh_totalindividual_1% (I have the expansion installed on version 4.2.0) and it doesn't show me anything, just stays as the placeholder instead of displaying the player name.

I know there's a player on the scoreboard because the placeholder %objective_score_totalindividual_for_entrypos_totalindividual_1% works perfectly and displays the score of the player but I want to display the player name

**Comment by EvModder** [comment]
You need the curly brackets (otherwise the expansion struggles to know where the player name ends, since player names can include underscores),

Side-note if you use "entryposhigh" it will pick the top entry by default so you can leave out the 1: `%objective_entryposhigh_{totalindividual}%`
similarly you could leave out the "high": `%objective_entrypos_{totalindividual}_{1}%`
technically due to the way the plugin handles defaults when unspecified you could leave out both: `%objective_entrypos_{totalindividual}%` although I find that less intuitive/readable.

**Comment by EvModder** [comment]
Also I recommend updating to v5.2 (the latest public release) or v6.0 (the latest beta/dev release), for better performance & more placeholders
