### ISSUE TITLE
Seems doesn't work on 1.20.4

### ISSUE THREAD

**Issue by StKillReal** [EvModder/EvStats#3]
![image](https://github.com/EvModder/EvStats/assets/60330193/6f0b06c6-c306-4b83-acb1-dd3a9d62c8df)
![image](https://github.com/EvModder/EvStats/assets/60330193/c7bf2fbc-58f3-4ce3-9860-8a64ad07f66a)
![image](https://github.com/EvModder/EvStats/assets/60330193/afc75530-ccc7-46ed-85a6-aed256bb6d4c)

I've checked other objectives and all of them return zero
![image](https://github.com/EvModder/EvStats/assets/60330193/4e9bc4ae-5bde-4195-aad4-5bc166f951ee)
![image](https://github.com/EvModder/EvStats/assets/60330193/e19d1995-0af6-4f87-b4a5-6d7f32dabb99)
![image](https://github.com/EvModder/EvStats/assets/60330193/38da718d-1bbb-4256-9f44-cd73e497fcb9)

**Comment by StKillReal** [comment]
@EvModder Is this an issue of ur plugin, or im doing something wrong? All has been working fine until I updated my server to 1.20.4

**Comment by EvModder** [comment]
Probably an issue of the plugin in that case; I think I saw a post about Scoreboard Mojang/Bukkit API changes in 1.20.4 and I haven't tested it myself yet. I'll try and do that tomorrow and hopefully get this fixed

Sorry I have been slow to respond (traveling for the holidays)

**Comment by StKillReal** [comment]
> Probably an issue of the plugin in that case; I think I saw a post about Scoreboard Mojang/Bukkit API changes in 1.20.4 and I haven't tested it myself yet. I'll try and do that tomorrow and hopefully get this fixed
> 
> Sorry I have been slow to respond (traveling for the holidays)

All started to work on latest paper build already, thank you ;)

**Comment by EvModder** [comment]
Ah okay!
Glad to hear it was an internal CB/Spigot/Paper API issue and they got it resolved (probably related to [the new scoreboard features](https://minecraft.wiki/w/Java_Edition_1.20.3#Command_format_2)).

I'm actually working on updating it today anyway, since there are some optimizations I've been wanting to make + new statistics to track in the newer versions of the game (e.g., "suspicious sand/gravel brushed")
